//! Generated by `resuma routes --generate` — do not edit by hand in new projects.

use resuma::flow::DiscoveredRoute;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
    fn routes() -> &'static [DiscoveredRoute] {
        &[
            DiscoveredRoute {
                pattern: "/",
                module: "index",
                component: "IndexPage",
                layouts: &["/"],
            },
            DiscoveredRoute {
                pattern: "/book",
                module: "book",
                component: "BookPage",
                layouts: &["/"],
            },
            DiscoveredRoute {
                pattern: "/gracias",
                module: "gracias",
                component: "GraciasPage",
                layouts: &["/"],
            },
        ]
    }
}
