// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
    fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
        match module {
            "index" => Some(super::index::page(req)),
            "audit::components" => Some(super::audit::components::index::page(req)),
            "audit::components::accessibility" => {
                Some(super::audit::components::accessibility::page(req))
            }
            "audit::components::clipboard" => Some(super::audit::components::clipboard::page(req)),
            "audit::components::client" => Some(super::audit::components::client::page(req)),
            "audit::components::context" => Some(super::audit::components::context::page(req)),
            "audit::components::control_flow" => {
                Some(super::audit::components::control_flow::page(req))
            }
            "audit::components::effects" => Some(super::audit::components::effects::page(req)),
            "audit::components::error_boundary" => {
                Some(super::audit::components::error_boundary::page(req))
            }
            "audit::components::form" => Some(super::audit::components::form::page(req)),
            "audit::components::handlers" => Some(super::audit::components::handlers::page(req)),
            "audit::components::islands" => Some(super::audit::components::islands::page(req)),
            "audit::components::js" => Some(super::audit::components::js::page(req)),
            "audit::components::nav_link" => Some(super::audit::components::nav_link::page(req)),
            "audit::components::picker" => Some(super::audit::components::picker::page(req)),
            "audit::components::server" => Some(super::audit::components::server::page(req)),
            "audit::components::signals" => Some(super::audit::components::signals::page(req)),
            "audit::components::slots" => Some(super::audit::components::slots::page(req)),
            "audit::components::store" => Some(super::audit::components::store::page(req)),
            "audit::components::tasks" => Some(super::audit::components::tasks::page(req)),
            "audit::components::testing" => Some(super::audit::components::testing::page(req)),
            "audit::components::view" => Some(super::audit::components::view::page(req)),
            "audit::cookbook" => Some(super::audit::cookbook::index::page(req)),
            "audit::cookbook::animations" => Some(super::audit::cookbook::animations::page(req)),
            "audit::cookbook::debouncer" => Some(super::audit::cookbook::debouncer::page(req)),
            "audit::cookbook::docker" => Some(super::audit::cookbook::docker::page(req)),
            "audit::cookbook::drag_drop" => Some(super::audit::cookbook::drag_drop::page(req)),
            "audit::cookbook::image_list" => Some(super::audit::cookbook::image_list::page(req)),
            "audit::cookbook::loader_invalidation" => {
                Some(super::audit::cookbook::loader_invalidation::page(req))
            }
            "audit::cookbook::portals" => Some(super::audit::cookbook::portals::page(req)),
            "audit::cookbook::prg" => Some(super::audit::cookbook::prg::page(req)),
            "audit::cookbook::streaming_loaders" => {
                Some(super::audit::cookbook::streaming_loaders::page(req))
            }
            "audit::cookbook::theme" => Some(super::audit::cookbook::theme::page(req)),
            "audit::cookbook::view_transitions" => {
                Some(super::audit::cookbook::view_transitions::page(req))
            }
            "audit::cookbook::virtual_list" => {
                Some(super::audit::cookbook::virtual_list::page(req))
            }
            "audit::flow" => Some(super::audit::flow::index::page(req)),
            "audit::flow::actions" => Some(super::audit::flow::actions::page(req)),
            "audit::flow::caching" => Some(super::audit::flow::caching::page(req)),
            "audit::flow::endpoints" => Some(super::audit::flow::endpoints::page(req)),
            "audit::flow::errors" => Some(super::audit::flow::errors::page(req)),
            "audit::flow::gestures" => Some(super::audit::flow::gestures::page(req)),
            "audit::flow::layouts" => Some(super::audit::flow::layouts::page(req)),
            "audit::flow::loaders" => Some(super::audit::flow::loaders::page(req)),
            "audit::flow::middleware" => Some(super::audit::flow::middleware::page(req)),
            "audit::flow::pages" => Some(super::audit::flow::pages::page(req)),
            "audit::flow::platform" => Some(super::audit::flow::platform::page(req)),
            "audit::flow::prefetch" => Some(super::audit::flow::prefetch::page(req)),
            "audit::flow::pwa" => Some(super::audit::flow::pwa::page(req)),
            "audit::flow::query_params" => Some(super::audit::flow::query_params::page(req)),
            "audit::flow::routing" => Some(super::audit::flow::routing::page(req)),
            "audit::flow::streaming" => Some(super::audit::flow::streaming::page(req)),
            "audit::flow::user_presence" => Some(super::audit::flow::user_presence::page(req)),
            "audit::flow::users::_id_" => Some(super::audit::flow::users::_id_::page(req)),
            "audit::integrations" => Some(super::audit::integrations::index::page(req)),
            "audit::integrations::auth" => Some(super::audit::integrations::auth::page(req)),
            "audit::integrations::e2e" => Some(super::audit::integrations::e2e::page(req)),
            "audit::integrations::i18n" => Some(super::audit::integrations::i18n::page(req)),
            "audit::integrations::network" => Some(super::audit::integrations::network::page(req)),
            "audit::integrations::og_image" => {
                Some(super::audit::integrations::og_image::page(req))
            }
            "audit::integrations::sqlx" => Some(super::audit::integrations::sqlx::page(req)),
            "audit::integrations::storage" => Some(super::audit::integrations::storage::page(req)),
            "audit::integrations::supabase" => {
                Some(super::audit::integrations::supabase::page(req))
            }
            "audit::integrations::tailwind" => {
                Some(super::audit::integrations::tailwind::page(req))
            }
            "audit::integrations::turso" => Some(super::audit::integrations::turso::page(req)),
            "audit::integrations::validator" => {
                Some(super::audit::integrations::validator::page(req))
            }
            "audit::intro" => Some(super::audit::intro::index::page(req)),
            "audit::intro::benchmark" => Some(super::audit::intro::benchmark::page(req)),
            "audit::intro::examples" => Some(super::audit::intro::examples::page(req)),
            "audit::intro::faq" => Some(super::audit::intro::faq::page(req)),
            "audit::intro::getting_started" => {
                Some(super::audit::intro::getting_started::page(req))
            }
            "audit::intro::project_structure" => {
                Some(super::audit::intro::project_structure::page(req))
            }
            "audit::reference::api" => Some(super::audit::reference::api::page(req)),
            "audit::reference::architecture" => {
                Some(super::audit::reference::architecture::page(req))
            }
            "audit::reference::cli" => Some(super::audit::reference::cli::page(req)),
            "audit::reference::matrix" => Some(super::audit::reference::matrix::page(req)),
            "audit::reference::registry" => Some(super::audit::reference::registry::page(req)),
            "audit::reference::package" => Some(super::audit::reference::package::page(req)),
            "audit::reference::reactivity" => Some(super::audit::reference::reactivity::page(req)),
            "audit::security" => Some(super::audit::security::index::page(req)),
            "audit::security::authorization" => {
                Some(super::audit::security::authorization::page(req))
            }
            "audit::security::backend_patterns" => {
                Some(super::audit::security::backend_patterns::page(req))
            }
            "audit::security::configure" => Some(super::audit::security::configure::page(req)),
            "audit::security::middleware" => Some(super::audit::security::middleware::page(req)),
            "audit::security::server_actions" => {
                Some(super::audit::security::server_actions::page(req))
            }
            "audit::security::todo" => Some(super::audit::security::todo::page(req)),
            _ => None,
        }
    }
}
