// Auto-generated by `resuma routes --generate`. Do not edit by hand.

pub mod audit {
    pub mod components {
        pub mod accessibility;
        pub mod client;
        pub mod clipboard;
        pub mod context;
        pub mod control_flow;
        pub mod effects;
        pub mod error_boundary;
        pub mod form;
        pub mod handlers;
        pub mod index;
        pub mod islands;
        pub mod js;
        pub mod nav_link;
        pub mod picker;
        pub mod server;
        pub mod signals;
        pub mod slots;
        pub mod store;
        pub mod tasks;
        pub mod testing;
        pub mod view;
    }
    pub mod cookbook {
        pub mod animations;
        pub mod debouncer;
        pub mod docker;
        pub mod drag_drop;
        pub mod image_list;
        pub mod index;
        pub mod loader_invalidation;
        pub mod portals;
        pub mod prg;
        pub mod streaming_loaders;
        pub mod theme;
        pub mod view_transitions;
        pub mod virtual_list;
    }
    pub mod flow {
        pub mod actions;
        pub mod caching;
        pub mod endpoints;
        pub mod errors;
        pub mod gestures;
        pub mod index;
        pub mod layouts;
        pub mod loaders;
        pub mod middleware;
        pub mod pages;
        pub mod platform;
        pub mod prefetch;
        pub mod pwa;
        pub mod query_params;
        pub mod routing;
        pub mod streaming;
        pub mod user_presence;
        pub mod users {
            #[path = "[id].rs"]
            pub mod _id_;
        }
    }
    pub mod integrations {
        pub mod auth;
        pub mod e2e;
        pub mod i18n;
        pub mod index;
        pub mod network;
        pub mod og_image;
        pub mod sqlx;
        pub mod storage;
        pub mod supabase;
        pub mod tailwind;
        pub mod turso;
        pub mod validator;
    }
    pub mod intro {
        pub mod benchmark;
        pub mod examples;
        pub mod faq;
        pub mod getting_started;
        pub mod index;
        pub mod project_structure;
    }
    pub mod reference {
        pub mod api;
        pub mod architecture;
        pub mod cli;
        pub mod matrix;
        pub mod package;
        pub mod reactivity;
        pub mod registry;
    }
    pub mod security {
        pub mod authorization;
        pub mod backend_patterns;
        pub mod configure;
        pub mod index;
        pub mod middleware;
        pub mod server_actions;
        pub mod todo;
    }
}
pub mod index;

mod _registry;
pub use _registry::PagesRegistry;
