// resuma-routes-fingerprint: b9a9a3c55059d09c
// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
    fn routes(&self) -> &'static [(&'static str, &'static str)] {
        &[("/", "index"), ("/about", "about")]
    }

    fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
        match module {
            "index" => Some(super::index::page(req)),
            "about" => Some(super::about::page(req)),
            _ => None,
        }
    }
}
