// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
match module {
            "index" => Some(super::index::page(req)),
            "docs" => Some(super::docs::index::page(req)),
            "docs::api" => Some(super::docs::api::page(req)),
            "docs::architecture" => Some(super::docs::architecture::page(req)),
            "docs::benchmark" => Some(super::docs::benchmark::page(req)),
            "docs::cli" => Some(super::docs::cli::page(req)),
            "docs::components" => Some(super::docs::components::index::page(req)),
            "docs::components::context" => Some(super::docs::components::context::page(req)),
            "docs::components::effects" => Some(super::docs::components::effects::page(req)),
            "docs::components::form" => Some(super::docs::components::form::page(req)),
            "docs::components::handlers" => Some(super::docs::components::handlers::page(req)),
            "docs::components::islands" => Some(super::docs::components::islands::page(req)),
            "docs::components::js" => Some(super::docs::components::js::page(req)),
            "docs::components::nav_link" => Some(super::docs::components::nav_link::page(req)),
            "docs::components::server" => Some(super::docs::components::server::page(req)),
            "docs::components::signals" => Some(super::docs::components::signals::page(req)),
            "docs::components::slots" => Some(super::docs::components::slots::page(req)),
            "docs::components::store" => Some(super::docs::components::store::page(req)),
            "docs::components::tasks" => Some(super::docs::components::tasks::page(req)),
            "docs::components::view" => Some(super::docs::components::view::page(req)),
            "docs::cookbook" => Some(super::docs::cookbook::index::page(req)),
            "docs::cookbook::debouncer" => Some(super::docs::cookbook::debouncer::page(req)),
            "docs::cookbook::docker" => Some(super::docs::cookbook::docker::page(req)),
            "docs::cookbook::portals" => Some(super::docs::cookbook::portals::page(req)),
            "docs::cookbook::streaming_loaders" => Some(super::docs::cookbook::streaming_loaders::page(req)),
            "docs::cookbook::theme" => Some(super::docs::cookbook::theme::page(req)),
            "docs::cookbook::view_transitions" => Some(super::docs::cookbook::view_transitions::page(req)),
            "docs::examples" => Some(super::docs::examples::page(req)),
            "docs::faq" => Some(super::docs::faq::page(req)),
            "docs::flow" => Some(super::docs::flow::index::page(req)),
            "docs::flow::caching" => Some(super::docs::flow::caching::page(req)),
            "docs::flow::endpoints" => Some(super::docs::flow::endpoints::page(req)),
            "docs::flow::errors" => Some(super::docs::flow::errors::page(req)),
            "docs::flow::layouts" => Some(super::docs::flow::layouts::page(req)),
            "docs::flow::loaders" => Some(super::docs::flow::loaders::page(req)),
            "docs::flow::middleware" => Some(super::docs::flow::middleware::page(req)),
            "docs::flow::pages" => Some(super::docs::flow::pages::page(req)),
            "docs::flow::routing" => Some(super::docs::flow::routing::page(req)),
            "docs::flow::streaming" => Some(super::docs::flow::streaming::page(req)),
            "docs::flow::submits" => Some(super::docs::flow::submits::page(req)),
            "docs::getting_started" => Some(super::docs::getting_started::page(req)),
            "docs::package" => Some(super::docs::package::page(req)),
            "docs::project_structure" => Some(super::docs::project_structure::page(req)),
            "docs::security" => Some(super::docs::security::index::page(req)),
            "docs::security::authorization" => Some(super::docs::security::authorization::page(req)),
            "docs::security::backend_patterns" => Some(super::docs::security::backend_patterns::page(req)),
            "docs::security::configure" => Some(super::docs::security::configure::page(req)),
            "docs::security::middleware" => Some(super::docs::security::middleware::page(req)),
            "docs::security::server_actions" => Some(super::docs::security::server_actions::page(req)),
            "docs::security::todo" => Some(super::docs::security::todo::page(req)),
            _ => None,
}
}
}
